### ISSUE TITLE
npm amd version tries to load angular more than once

### ISSUE THREAD

**Issue by robertbaker** [adjohnson916/ng-click-select#5]
Look how I did it here: https://github.com/robertbaker/angular-numbro/blob/master/angular-numbro.js

Getting a console message that says trying to load angular more than once and pinned it down to this.

**Comment by adjohnson916** [comment]
Related to #4.

**Comment by adjohnson916** [comment]
@robertbaker, regarding that code:

```js
76		angularNumbro(angular, require('numbro'));
77		module.exports = 'angularNumbro';
```

Looks like you're relying on `angular` already being in the global scope, so probably `window.angular`? How can you guarantee Angular is already loaded if there is no indication that it's a dependency via a `require('angular')` as I have done? Wouldn't Browserify not necessarily know to package the scripts in the correct execution order? Perhaps there is some other convention for Angular modules via npm and/or Browserify of which neither of us is aware?

Also, as a side note, why do you assign a string value to `module.exports`? Is that some convention or requirement for Browserify? I guess it doesn't matter since you don't really need to export anything, just to register your module with Angular.

**Comment by robertbaker** [comment]
I ripped the wrapper from angular-moment (think it was that).
I'm delaying the bootstrap of my app, I'm using systemjs instead of browserify.

I'll add a require angular to mine. Not sure if that will cause angular to load, hope not.

**Comment by adjohnson916** [comment]
@robertbaker, please let me know if you find out anything else.

**Comment by robertbaker** [comment]
@adjohnson916 I couldn't resolve this without modifying your wrapper.

IMO it's safe to assume angular is loaded for directives. You can't use an angular directive without angular. You shouldn't run into any script order issues either.

**Comment by adjohnson916** [comment]
@robertbaker Probably right. I'll try to reproduce the issue when I can. It may be a bug with Angular - there seems to be a strong convention that node modules can be required multiple times without side effect.

**Comment by adjohnson916** [comment]
@robertbaker What version of angular are you using?

I have an example with browersify that's working fine when I require angular in my root file, despite that the current version of ng-click-select also requires angular itself. See https://adjohnson916.github.io/ng-click-select-node-test/ from https://github.com/adjohnson916/ng-click-select-node-test.

Is your code available anywhere for review?

**Comment by robertbaker** [comment]
Seems to be related to the dependency of npm angular and jspm uses github.

https://github.com/jspm/jspm-cli/issues/1132

**Comment by adjohnson916** [comment]
Thanks for reporting back, @robertbaker. I don't use jspm, so that would explain it.
